---
# - This is a change for me to see how it all works 
#
- name: Deploy Tomcat on Debian hosts
  hosts: debian_tomcat
  become: yes
  vars:
    ansible_become_method: sudo
  serial: 2          # rolling: 2 hosts at a time
  roles:
    - tomcat

# - name: Deploy Tomcat on Debian hosts
#   hosts: debian_tomcat
#   become: yes
#   vars:
#     ansible_become_method: sudo
#   roles:
#     - tomcat
