---
  # - Thisddd is a change for me to see how it all works
  # - Thisddd is a change for me to see how it all works 
  # - This is fourth-pr-practice test change"
- name: Deploy Tomcat on Debian hosts
  hosts: debian_tomcat
  become: false
  vars:
    ansible_become_method: sudo
  serial: 2          # rolling: 2 hosts at a time
  roles:
    - tomcat

# - name: Deploy Tomcat on Debian hosts
#   hosts: debian_tomcat
#   become: yes
#   vars:
#     ansible_become_method: sudo
#   roles:
#     - tomcat
